[package]
name = "rumdump"
version = "0.1.0"
edition = "2021"


[dependencies]
bitpack = { version = "0.1.0", path = "../bitpack" }
num-derive = "0.4"
num-traits = "0.2"

[features]
cargo-clippy = []
